CREATE TABLE IF NOT EXISTS outbox (
    id UUID PRIMARY KEY,
    topic VARCHAR(31) NOT NULL,
    payload JSONB NOT NULL,
    send_time TIMESTAMP WITH TIME ZONE NOT NULL,
    send_status BOOLEAN NOT NULL DEFAULT FALSE
);