CREATE TABLE IF NOT EXISTS "Tables" (
	"table_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"restaurant_id" INTEGER NOT NULL,
	"table_number" VARCHAR(255),
	"seats_number" INTEGER NOT NULL,
	"type" TABLE_TYPE NOT NULL,
	"shape" TABLE_SHAPE NOT NULL,
	PRIMARY KEY("table_id"),
	FOREIGN KEY ("restaurant_id") REFERENCES "Restaurants"("restaurant_id") ON DELETE CASCADE
);