CREATE TABLE IF NOT EXISTS "positions" (
	"table_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"type" VARCHAR(63),
	PRIMARY KEY("table_id"),
	FOREIGN KEY ("restaurant_id") REFERENCES "restaurants"("restaurant_id") ON DELETE CASCADE
);