// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/reservations/:table_id/free-times": {
            "get": {
                "description": "Возвращает список свободных временных интервалов для бронирования указанного столика.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking"
                ],
                "summary": "Получить свободные временные интервалы для столика",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID столика",
                        "name": "table_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.TimeSlotResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/reservations/free-tables": {
            "get": {
                "description": "Возвращает список доступных столиков на указанный период",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking"
                ],
                "summary": "Получить список свободных столиков",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Начало периода бронирования (в формате RFC3339)",
                        "name": "reservation_time_from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Конец периода бронирования (в формате RFC3339)",
                        "name": "reservation_time_to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.FreeTableResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/reservations/new-reservation": {
            "post": {
                "description": "Эта функция выполняет бронирование столика для пользователя на указанный период времени.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking"
                ],
                "summary": "Бронирование столика",
                "parameters": [
                    {
                        "description": "Информация о бронировании",
                        "name": "reservation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ReservationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/reservations/user": {
            "get": {
                "description": "Возвращает список всех бронирований, сделанных пользователем, включая информацию о ресторане и столике.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Получение всех бронирований пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "user_id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.UserReservationResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tables/new-table": {
            "post": {
                "description": "Создаёт новый столик в ресторане и сохраняет его позицию, если координаты указаны",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Добавить столик",
                "parameters": [
                    {
                        "description": "Информация о столике",
                        "name": "table",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateTableRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Столик добавлен",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка при добавлении столика",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CreateTableRequest": {
            "type": "object",
            "required": [
                "restaurant_id",
                "seats_number",
                "shape",
                "type"
            ],
            "properties": {
                "restaurant_id": {
                    "type": "integer"
                },
                "seats_number": {
                    "type": "integer"
                },
                "shape": {
                    "description": "ENUM TABLE_SHAPE",
                    "type": "string"
                },
                "table_number": {
                    "type": "string"
                },
                "type": {
                    "description": "ENUM TABLE_TYPE",
                    "type": "string"
                },
                "x": {
                    "description": "Координаты опционально",
                    "type": "integer"
                },
                "y": {
                    "type": "integer"
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "dto.FreeTableResponse": {
            "type": "object",
            "properties": {
                "restaurant_name": {
                    "type": "string"
                },
                "seats_number": {
                    "type": "integer"
                },
                "table_id": {
                    "type": "integer"
                },
                "table_number": {
                    "type": "integer"
                }
            }
        },
        "dto.ReservationRequest": {
            "type": "object",
            "properties": {
                "reservation_time_from": {
                    "description": "Время начала бронирования (RFC3339)",
                    "type": "string"
                },
                "reservation_time_to": {
                    "description": "Время окончания бронирования (RFC3339)",
                    "type": "string"
                },
                "table_id": {
                    "description": "Идентификатор столика",
                    "type": "integer"
                },
                "user_id": {
                    "description": "Идентификатор пользователя",
                    "type": "integer"
                }
            }
        },
        "dto.TimeSlotResponse": {
            "type": "object",
            "properties": {
                "free_from": {
                    "type": "string"
                },
                "free_until": {
                    "type": "string"
                }
            }
        },
        "dto.UserReservationResponse": {
            "type": "object",
            "properties": {
                "reservation_id": {
                    "type": "integer"
                },
                "reservation_time_from": {
                    "type": "string"
                },
                "reservation_time_to": {
                    "type": "string"
                },
                "restaurant_name": {
                    "type": "string"
                },
                "seats_number": {
                    "type": "integer"
                },
                "table_id": {
                    "type": "integer"
                },
                "table_number": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Restorio API",
	Description:      "API для бронирования столиков",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
